steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/medster-backend', '-f', 'Dockerfile.backend', '.']

  # Build Frontend (with backend URL baked in at build time)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/medster-frontend'
      - '-f'
      - 'Dockerfile.frontend'
      - '--build-arg'
      - 'NEXT_PUBLIC_BACKEND_URL=https://medster-backend-430915582144.us-central1.run.app'
      - '.'

  # Push Images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/medster-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/medster-frontend']

  # Deploy Backend to Cloud Run (uses GCS for Coherent Data Set)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'medster-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/medster-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'USE_GCS=true,GCS_COHERENT_BUCKET=medster-coherent-data'
      - '--set-secrets'
      - 'ANTHROPIC_API_KEY=anthropic-api-key:latest'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--port'
      - '8000'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'medster-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/medster-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NEXTAUTH_SECRET=kYMZd8pQwGazB0DRxyIQ7EK8wyzkvTaPJvYoXbWr9nA=,NEXTAUTH_URL=https://medster-frontend-430915582144.us-central1.run.app'

images:
  - 'gcr.io/$PROJECT_ID/medster-backend'
  - 'gcr.io/$PROJECT_ID/medster-frontend'
